- name: Verify
  hosts: all
  vars:
    expected_output: "v1.21.2"
  tasks:
    - name: Execute kubectl version to capture output
      command: "kubectl version --client"
      register: kubectl_version_output
      changed_when: false

    - name: Ensure kubectl version output contains correct version string
      assert:
        that:
          - "expected_output in kubectl_version_output.stdout"